/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

//fibonacciSeq = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89];
fibonacciSeq = [1, 2, 3];

//GERAR SEQUÊNCIA DE FIBONACCI < 4.000.000
var i;
for (i = 3; i < 100; i++) {
  const nextNumber = fibonacciSeq[i - 1] + fibonacciSeq[i - 2];
  if (nextNumber < 4000000) fibonacciSeq.push(nextNumber);
}

//FILTRAR APENAS OS NÚMEROS PARES
let evenFibonacci = fibonacciSeq.filter((item) => {
  return item % 2 == 0;
});

//SOMAR O ARRAY DE NÚMEROS PARES
console.log(evenFibonacci.reduce((a, b) => a + b, 0));
